// data_center.js

const weatherData = [
  // Monday
  { day: "Monday", hour: "00:00", weather: "cloudy" },
  { day: "Monday", hour: "01:00", weather: "cloudy" },
  { day: "Monday", hour: "02:00", weather: "rain" },
  { day: "Monday", hour: "03:00", weather: "rain" },
  { day: "Monday", hour: "04:00", weather: "rain" },
  { day: "Monday", hour: "05:00", weather: "cloudy" },
  { day: "Monday", hour: "06:00", weather: "sunny" },
  { day: "Monday", hour: "07:00", weather: "sunny" },
  { day: "Monday", hour: "08:00", weather: "sunny" },
  { day: "Monday", hour: "09:00", weather: "sunny" },
  { day: "Monday", hour: "10:00", weather: "sunny" },
  { day: "Monday", hour: "11:00", weather: "sunny" },
  { day: "Monday", hour: "12:00", weather: "sunny" },
  { day: "Monday", hour: "13:00", weather: "sunny" },
  { day: "Monday", hour: "14:00", weather: "cloudy" },
  { day: "Monday", hour: "15:00", weather: "cloudy" },
  { day: "Monday", hour: "16:00", weather: "rain" },
  { day: "Monday", hour: "17:00", weather: "rain" },
  { day: "Monday", hour: "18:00", weather: "cloudy" },
  { day: "Monday", hour: "19:00", weather: "cloudy" },
  { day: "Monday", hour: "20:00", weather: "cloudy" },
  { day: "Monday", hour: "21:00", weather: "rain" },
  { day: "Monday", hour: "22:00", weather: "rain" },
  { day: "Monday", hour: "23:00", weather: "cloudy" },

  // Tuesday
  { day: "Tuesday", hour: "00:00", weather: "cloudy" },
  { day: "Tuesday", hour: "01:00", weather: "rain" },
  { day: "Tuesday", hour: "02:00", weather: "rain" },
  { day: "Tuesday", hour: "03:00", weather: "cloudy" },
  { day: "Tuesday", hour: "04:00", weather: "cloudy" },
  { day: "Tuesday", hour: "05:00", weather: "sunny" },
  { day: "Tuesday", hour: "06:00", weather: "sunny" },
  { day: "Tuesday", hour: "07:00", weather: "sunny" },
  { day: "Tuesday", hour: "08:00", weather: "sunny" },
  { day: "Tuesday", hour: "09:00", weather: "sunny" },
  { day: "Tuesday", hour: "10:00", weather: "sunny" },
  { day: "Tuesday", hour: "11:00", weather: "sunny" },
  { day: "Tuesday", hour: "12:00", weather: "sunny" },
  { day: "Tuesday", hour: "13:00", weather: "cloudy" },
  { day: "Tuesday", hour: "14:00", weather: "cloudy" },
  { day: "Tuesday", hour: "15:00", weather: "cloudy" },
  { day: "Tuesday", hour: "16:00", weather: "rain" },
  { day: "Tuesday", hour: "17:00", weather: "rain" },
  { day: "Tuesday", hour: "18:00", weather: "cloudy" },
  { day: "Tuesday", hour: "19:00", weather: "cloudy" },
  { day: "Tuesday", hour: "20:00", weather: "rain" },
  { day: "Tuesday", hour: "21:00", weather: "rain" },
  { day: "Tuesday", hour: "22:00", weather: "cloudy" },
  { day: "Tuesday", hour: "23:00", weather: "cloudy" },

  // Wednesday
  { day: "Wednesday", hour: "00:00", weather: "rain" },
  { day: "Wednesday", hour: "01:00", weather: "rain" },
  { day: "Wednesday", hour: "02:00", weather: "rain" },
  { day: "Wednesday", hour: "03:00", weather: "cloudy" },
  { day: "Wednesday", hour: "04:00", weather: "cloudy" },
  { day: "Wednesday", hour: "05:00", weather: "cloudy" },
  { day: "Wednesday", hour: "06:00", weather: "sunny" },
  { day: "Wednesday", hour: "07:00", weather: "sunny" },
  { day: "Wednesday", hour: "08:00", weather: "sunny" },
  { day: "Wednesday", hour: "09:00", weather: "sunny" },
  { day: "Wednesday", hour: "10:00", weather: "sunny" },
  { day: "Wednesday", hour: "11:00", weather: "sunny" },
  { day: "Wednesday", hour: "12:00", weather: "sunny" },
  { day: "Wednesday", hour: "13:00", weather: "sunny" },
  { day: "Wednesday", hour: "14:00", weather: "sunny" },
  { day: "Wednesday", hour: "15:00", weather: "cloudy" },
  { day: "Wednesday", hour: "16:00", weather: "cloudy" },
  { day: "Wednesday", hour: "17:00", weather: "rain" },
  { day: "Wednesday", hour: "18:00", weather: "rain" },
  { day: "Wednesday", hour: "19:00", weather: "cloudy" },
  { day: "Wednesday", hour: "20:00", weather: "cloudy" },
  { day: "Wednesday", hour: "21:00", weather: "cloudy" },
  { day: "Wednesday", hour: "22:00", weather: "rain" },
  { day: "Wednesday", hour: "23:00", weather: "rain" },

  // Thursday
  { day: "Thursday", hour: "00:00", weather: "rain" },
  { day: "Thursday", hour: "01:00", weather: "cloudy" },
  { day: "Thursday", hour: "02:00", weather: "cloudy" },
  { day: "Thursday", hour: "03:00", weather: "cloudy" },
  { day: "Thursday", hour: "04:00", weather: "sunny" },
  { day: "Thursday", hour: "05:00", weather: "sunny" },
  { day: "Thursday", hour: "06:00", weather: "sunny" },
  { day: "Thursday", hour: "07:00", weather: "sunny" },
  { day: "Thursday", hour: "08:00", weather: "sunny" },
  { day: "Thursday", hour: "09:00", weather: "sunny" },
  { day: "Thursday", hour: "10:00", weather: "sunny" },
  { day: "Thursday", hour: "11:00", weather: "sunny" },
  { day: "Thursday", hour: "12:00", weather: "sunny" },
  { day: "Thursday", hour: "13:00", weather: "cloudy" },
  { day: "Thursday", hour: "14:00", weather: "cloudy" },
  { day: "Thursday", hour: "15:00", weather: "rain" },
  { day: "Thursday", hour: "16:00", weather: "rain" },
  { day: "Thursday", hour: "17:00", weather: "rain" },
  { day: "Thursday", hour: "18:00", weather: "cloudy" },
  { day: "Thursday", hour: "19:00", weather: "cloudy" },
  { day: "Thursday", hour: "20:00", weather: "cloudy" },
  { day: "Thursday", hour: "21:00", weather: "rain" },
  { day: "Thursday", hour: "22:00", weather: "rain" },
  { day: "Thursday", hour: "23:00", weather: "cloudy" },

  // Friday
  { day: "Friday", hour: "00:00", weather: "cloudy" },
  { day: "Friday", hour: "01:00", weather: "cloudy" },
  { day: "Friday", hour: "02:00", weather: "cloudy" },
  { day: "Friday", hour: "03:00", weather: "rain" },
  { day: "Friday", hour: "04:00", weather: "rain" },
  { day: "Friday", hour: "05:00", weather: "cloudy" },
  { day: "Friday", hour: "06:00", weather: "sunny" },
  { day: "Friday", hour: "07:00", weather: "sunny" },
  { day: "Friday", hour: "08:00", weather: "sunny" },
  { day: "Friday", hour: "09:00", weather: "sunny" },
  { day: "Friday", hour: "10:00", weather: "sunny" },
  { day: "Friday", hour: "11:00", weather: "sunny" },
  { day: "Friday", hour: "12:00", weather: "sunny" },
  { day: "Friday", hour: "13:00", weather: "sunny" },
  { day: "Friday", hour: "14:00", weather: "cloudy" },
  { day: "Friday", hour: "15:00", weather: "cloudy" },
  { day: "Friday", hour: "16:00", weather: "rain" },
  { day: "Friday", hour: "17:00", weather: "rain" },
  { day: "Friday", hour: "18:00", weather: "cloudy" },
  { day: "Friday", hour: "19:00", weather: "cloudy" },
  { day: "Friday", hour: "20:00", weather: "rain" },
  { day: "Friday", hour: "21:00", weather: "rain" },
  { day: "Friday", hour: "22:00", weather: "cloudy" },
  { day: "Friday", hour: "23:00", weather: "cloudy" },

  // Saturday
  { day: "Saturday", hour: "00:00", weather: "rain" },
  { day: "Saturday", hour: "01:00", weather: "rain" },
  { day: "Saturday", hour: "02:00", weather: "cloudy" },
  { day: "Saturday", hour: "03:00", weather: "cloudy" },
  { day: "Saturday", hour: "04:00", weather: "cloudy" },
  { day: "Saturday", hour: "05:00", weather: "sunny" },
  { day: "Saturday", hour: "06:00", weather: "sunny" },
  { day: "Saturday", hour: "07:00", weather: "sunny" },
  { day: "Saturday", hour: "08:00", weather: "sunny" },
  { day: "Saturday", hour: "09:00", weather: "sunny" },
  { day: "Saturday", hour: "10:00", weather: "sunny" },
  { day: "Saturday", hour: "11:00", weather: "sunny" },
  { day: "Saturday", hour: "12:00", weather: "sunny" },
  { day: "Saturday", hour: "13:00", weather: "sunny" },
  { day: "Saturday", hour: "14:00", weather: "cloudy" },
  { day: "Saturday", hour: "15:00", weather: "cloudy" },
  { day: "Saturday", hour: "16:00", weather: "rain" },
  { day: "Saturday", hour: "17:00", weather: "rain" },
  { day: "Saturday", hour: "18:00", weather: "cloudy" },
  { day: "Saturday", hour: "19:00", weather: "cloudy" },
  { day: "Saturday", hour: "20:00", weather: "rain" },
  { day: "Saturday", hour: "21:00", weather: "rain" },
  { day: "Saturday", hour: "22:00", weather: "cloudy" },
  { day: "Saturday", hour: "23:00", weather: "cloudy" },

  // Sunday
  { day: "Sunday", hour: "00:00", weather: "cloudy" },
  { day: "Sunday", hour: "01:00", weather: "rain" },
  { day: "Sunday", hour: "02:00", weather: "rain" },
  { day: "Sunday", hour: "03:00", weather: "cloudy" },
  { day: "Sunday", hour: "04:00", weather: "cloudy" },
  { day: "Sunday", hour: "05:00", weather: "sunny" },
  { day: "Sunday", hour: "06:00", weather: "sunny" },
  { day: "Sunday", hour: "07:00", weather: "sunny" },
  { day: "Sunday", hour: "08:00", weather: "sunny" },
  { day: "Sunday", hour: "09:00", weather: "sunny" },
  { day: "Sunday", hour: "10:00", weather: "sunny" },
  { day: "Sunday", hour: "11:00", weather: "sunny" },
  { day: "Sunday", hour: "12:00", weather: "sunny" },
  { day: "Sunday", hour: "13:00", weather: "cloudy" },
  { day: "Sunday", hour: "14:00", weather: "cloudy" },
  { day: "Sunday", hour: "15:00", weather: "rain" },
  { day: "Sunday", hour: "16:00", weather: "rain" },
  { day: "Sunday", hour: "17:00", weather: "rain" },
  { day: "Sunday", hour: "18:00", weather: "cloudy" },
  { day: "Sunday", hour: "19:00", weather: "cloudy" },
  { day: "Sunday", hour: "20:00", weather: "cloudy" },
  { day: "Sunday", hour: "21:00", weather: "rain" },
  { day: "Sunday", hour: "22:00", weather: "rain" },
  { day: "Sunday", hour: "23:00", weather: "cloudy" },
];

export default weatherData;
